default: &default
  adapter: postgresql
  encoding: unicode
  database: "postgres"
  #<%= ENV['DATABASE_NAME'] %>
  # username: "praveenkumar"
  # password: "Praveen@16"
  port: 5432
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  #database: codejudge_dev

test:
  <<: *default
  database: codejudge_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
